[package]
name = "markdown-all-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "markdown-all"
path = "src/main.rs"

[dependencies]
markdown-all = { path = "../markdown-all" }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
